#!/bin/sh

# Dependencies:
# imagemagick
# scrot
# i3lock
 
IMAGE=/tmp/i3lock.png

# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
#BLURTYPE="0x5" # 7.52s
BLURTYPE="0x2" # 4.39s
#BLURTYPE="5x3" # 3.80s
#BLURTYPE="2x8" # 2.90s
#BLURTYPE="2x3" # 2.92s

scrot $IMAGE && convert $IMAGE - \
                        level 0%,100%,0.6 -blur $BLURTYPE - | \
        composite -gravity center ~/Pictures/lock.png - $IMAGE && i3lock -i $IMAGE
