#!/bin/sh

# current_file_=$(readlink -f "$0")
# current_dir_=$(dirname ${current_file_})


# Backup if Xmodmap exists
test -f ~/.Xmodmap && (
    echo "> Backing up: Xmodmap -> Xmodmap.bak"
    mv ~/.Xmodmap ~/.Xmodmap.bak
)
test -f ~/.Xmodmap.altgr && (
    echo "> Backing up: Xmodmap.altgr -> Xmodmap.altgr.bak"
    mv ~/.Xmodmap.altgr ~/.Xmodmap.altgr.bak
)

# Generate new Xmodmap
echo "> Generating Xmodmap: Programmer Dvorak + Escape/CapsLock swapped + Ctrl/Alt swapped"
echo "! -*- mode: xmodmap-generic -*-" > ~/.Xmodmap
cat xmodmap/Xmodmap-correct-Super \
    xmodmap/Xmodmap-swap-CapsLock-Escape \
    xmodmap/Xmodmap-swap-Control-Alt \
    xmodmap/Xmodmap-double-shift-make-caps \
    >> ~/.Xmodmap

# Xmodmap with AltGr
echo "> Generating Xmodmap: Programmer Dvorak + right AtlGr + Escape/CapsLock swapped + Ctrl/Alt swapped"
echo "! -*- mode: xmodmap-generic -*-" > ~/.Xmodmap.altgr
cat xmodmap/Xmodmap-correct-Super \
    xmodmap/Xmodmap-swap-CapsLock-Escape \
    xmodmap/Xmodmap-swap-Control-Alt \
    xmodmap/Xmodmap-double-shift-make-caps \
    xmodmap/Xmodmap-add-right-AltGr \
    >> ~/.Xmodmap.altgr
sed -i 's/add mod1 = Alt_R//' ~/.Xmodmap.altgr
